spring.application.name=PCB4

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=NewPass@2026!
spring.datasource.url=jdbc:mysql://106.53.29.207:3306/blog_manager?serverTimezone=Asia/Shanghai
spring.datasource.name=defaultDataSource

server.port=8081

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.entity

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000



